# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/protobuf/rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16src/protobuf/rpc.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t*1\n\x0bHelloStatus\x12\x0c\n\x08HELLO_OK\x10\x00\x12\x14\n\x10HELLO_DISMATCHED\x10\x01\x32:\n\x11MultiplayerOnline\x12%\n\x05Hello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x42\x03\xf8\x01\x01\x62\x06proto3')

_HELLOSTATUS = DESCRIPTOR.enum_types_by_name['HelloStatus']
HelloStatus = enum_type_wrapper.EnumTypeWrapper(_HELLOSTATUS)
HELLO_OK = 0
HELLO_DISMATCHED = 1


_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'src.protobuf.rpc_pb2'
  # @@protoc_insertion_point(class_scope:HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'src.protobuf.rpc_pb2'
  # @@protoc_insertion_point(class_scope:HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

_MULTIPLAYERONLINE = DESCRIPTOR.services_by_name['MultiplayerOnline']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001'
  _HELLOSTATUS._serialized_start=87
  _HELLOSTATUS._serialized_end=136
  _HELLOREQUEST._serialized_start=26
  _HELLOREQUEST._serialized_end=54
  _HELLOREPLY._serialized_start=56
  _HELLOREPLY._serialized_end=85
  _MULTIPLAYERONLINE._serialized_start=138
  _MULTIPLAYERONLINE._serialized_end=196
# @@protoc_insertion_point(module_scope)
