# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.protobuf import rpc_pb2 as src_dot_protobuf_dot_rpc__pb2


class MultiplayerOnlineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
                '/MultiplayerOnline/Hello',
                request_serializer=src_dot_protobuf_dot_rpc__pb2.HelloRequest.SerializeToString,
                response_deserializer=src_dot_protobuf_dot_rpc__pb2.HelloReply.FromString,
                )


class MultiplayerOnlineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Hello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MultiplayerOnlineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=src_dot_protobuf_dot_rpc__pb2.HelloRequest.FromString,
                    response_serializer=src_dot_protobuf_dot_rpc__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MultiplayerOnline', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MultiplayerOnline(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MultiplayerOnline/Hello',
            src_dot_protobuf_dot_rpc__pb2.HelloRequest.SerializeToString,
            src_dot_protobuf_dot_rpc__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
